---
title: "UBC iGEM 2022 - Differential Expression Analysis"
output:
  html_document:
    df_print: paged
---
### Differential Expression Workflow:
1. Read in the Data
2. Create a DGEList Object
3. Filter
4. Normalize
5. Estimate Dispersions
6. Differential Expression

```{r, results='hide', message=FALSE, warning=FALSE}
library(tidyverse)
library(edgeR)
library(limma)
library(dplyr)
library(biomaRt)
library(ggplot2)
library(ggVennDiagram)

x <- read.delim("../data/SRP045409_count.tsv.gz", row.names="gene")
x <- x %>% rename(HD_6h_1=SRR1542417, HD_6h_2=SRR1542416, HD_1h_1=SRR1542415, HD_1h_2=SRR1542414, H_6h_1=SRR1542413, H_6h_2=SRR1542412, H_1h_1=SRR1542411, H_1h_2=SRR1542410, D_6h_1=SRR1542409, D_6h_2=SRR1542408, D_1h_1=SRR1542407, D_1h_2=SRR1542406, ctrl_1=SRR1542405, ctrl_2=SRR1542404)
```

```{r}
# filter out LC (low confidence) genes: https://plants.ensembl.org/Triticum_aestivum/Info/Annotation/
x <- x %>% filter(!grepl("LC", row.names(x), fixed=TRUE))

# round counts to nearest integer
x <- round(x)

d <- DGEList(counts=x, 
             group=factor(
               c("HD_6h", "HD_6h", "HD_1h", "HD_1h", "H_6h", "H_6h", "H_1h", "H_1h", "D_6h", "D_6h", "D_1h", "D_1h", "ctrl", "ctrl")))

keep <- filterByExpr(d)
d <- d[keep, , keep.lib.sizes=FALSE]
d <- calcNormFactors(d)
d <- estimateDisp(d)
```

### Comparing Differentially Expressed Genes (DEGs) b/w Stress Conditions:

```{r}
# define function
pairwise_comparison <- function(experimental_condition) {
  et_exp_ctrl <- exactTest(d, pair=c("ctrl", experimental_condition))
  et_exp_ctrl$table$padj <- p.adjust(et_exp_ctrl$table$PValue, method="BH")
  return(et_exp_ctrl)
}

et_HD6H_ctrl <- pairwise_comparison("HD_6h")
et_H6H_ctrl <- pairwise_comparison("H_6h")
et_D6H_ctrl <- pairwise_comparison("D_6h")
```
```{r}
# comparing genes that are significantly upregulated in experimental condition
fdr = 0.001
lfc = 5

upRegGenes <- list(
  HD_6H = row.names(et_HD6H_ctrl$table %>% filter(et_HD6H_ctrl$table$padj < fdr & et_HD6H_ctrl$table$logFC > lfc)), 
  H_6H = row.names(et_H6H_ctrl$table %>% filter(et_H6H_ctrl$table$padj < fdr & et_H6H_ctrl$table$logFC > lfc)),
  D_6H = row.names(et_D6H_ctrl$table %>% filter(et_D6H_ctrl$table$padj < fdr & et_D6H_ctrl$table$logFC > lfc)))

ggVennDiagram(upRegGenes, label_alpha = 0, label_color="white", set_size=3, edge_size=1.5) + ggtitle("Comparing Upregulated Genes b/w Stress Conditions") + theme(plot.title = element_text(hjust=0.5))
```
```{r}
# to see which genes reside in which Venn Diagram region
upRegGenes_Venn_values <- process_region_data(Venn(upRegGenes))
upRegGenes_Venn_values
```
```{r}
upRegGenes_Venn_values$item <- vapply(upRegGenes_Venn_values$item, paste, collapse = ", ", character(1L))
write.csv(upRegGenes_Venn_values, "upRegGenes_Venn_values.csv", row.names = FALSE)
```

```{r}
# comparing genes that are significantly downregulated in experimental condition
downRegGenes <- list(
  HD_6H = row.names(et_HD6H_ctrl$table %>% filter(et_HD6H_ctrl$table$padj < fdr & et_HD6H_ctrl$table$logFC < -lfc)), 
  H_6H = row.names(et_H6H_ctrl$table %>% filter(et_H6H_ctrl$table$padj < fdr & et_H6H_ctrl$table$logFC < -lfc)),
  D_6H = row.names(et_D6H_ctrl$table %>% filter(et_D6H_ctrl$table$padj < fdr & et_D6H_ctrl$table$logFC < -lfc)))

ggVennDiagram(downRegGenes, label_alpha = 0, label_color="white", set_size=3, edge_size=1.5) + ggtitle("Comparing Downregulated Genes b/w Stress Conditions") + theme(plot.title = element_text(hjust=0.5))
```
```{r}
# to see which genes reside in which Venn Diagram region
downRegGenes_Venn_values <- process_region_data(Venn(downRegGenes))
downRegGenes_Venn_values
```
```{r}
downRegGenes_Venn_values$item <- vapply(downRegGenes_Venn_values$item, paste, collapse = ", ", character(1L))
write.csv(downRegGenes_Venn_values, "downRegGenes_Venn_values.csv", row.names = FALSE)
```
